language: node_js
node_js:
  - 'stable'
env:
  global:
    - a83a409f2a689be50b05870658231b712a58e822c067298fa51d7fc8ad165912
cache:
  directories: [node_modules]
services: 
  - postgresql
before_script:
  - psql -c 'create database new_teamwork;' -U postgres
script:
  - npm test
  - npm install
after_script:
  - npm run coverage